version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - checkout
      - run:
        name: Execute Docker Build
        command: docker build .

workflows:
  build-test-deploy:
    jobs:
      - build-test
