version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Execute Docker Build
          command: docker build .

workflows:
  build_test_deploy:
    jobs:
      - build_test